version: '3'
services:
  api:
    tty: true
    command: start
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/opt/app/server
    ports:
      - 3001:3001
    environment:
      - SHELL=/bin/sh  
